### PR TITLE
Implement deis domains removal/adding

### PR DESCRIPTION
**Pull request by nathansamson**

### CODE REVIEW

**Comment by 0x203** [comment]
Thank you!
And good luck using this!

**Comment by nathansamson** [comment]
Its been doing its job for now... Not doing a great job (at all) in abstracting the the repsonses, but thats fine for the app I am writing :)

**Comment by franzliedke** [comment]
Thanks, @nathansamson!

Can you show us an example of the kind of response abstraction you'd like to see? Maybe another API wrapper somewhere...

**Comment by nathansamson** [comment]
Not sure what I expect.

One of my main problems would have been with error handling, but that is actually handled pretty well

I would expect all responses to be wrapped in a sensible format (not a hash key). This would make it more intuitive to work with the API. Now you need to know the API itself, before you can start using to extract the right hash values. Also pagination is left up to the user as well...

Being able to write code like this might also be handy and more Object Oriented

```
app = client.application('app name')
app.releases.each do |release| # note that this also takes care of pagination (when necessary)
  puts release.version
end

app.domains.add('new.domain.com')
```

Obviously it is pretty trivial to write such an API wrapper on top of this base layer, so maybe this is an idea for another project.

Anyway I am only using 2 or 3 API calls right now, so the bare minimum is working fine for me right now

If you want to discuss this further I propose opening a issue for that...

**Pull request merged**
