### PR TITLE
Creating certificates

### PR DESCRIPTION
**Pull request by kostassof**

### CODE REVIEW

**Comment by franzliedke** [comment]
@kostassof Great, thank you! Are you using this library successfully?

@0x203 Could you take care of merging and releasing a new version? :)

**Comment by nathansamson** [comment]
Thanks @franzliedke 

We have been using this library successfully on our (legacy) deis service. Note that we discovered a problem in the change + we are also going to need the other certificate operations so we will come with an updated pull request, so please do not merge yet

To clarify: I am a co-worker of kostassof :)

**Comment by kostassof** [comment]
@franzliedke The pull request has been updated with remove certificate operation as well. The following days 1) list all certificates & 2) list certificate details will be added.

**Comment by franzliedke** [comment]
@kostassof Do you consider this complete? As far as I can see, all operations you mentioned as planned seem to have been added.

**Comment by kostassof** [comment]
Hey @franzliedke. I'm sorry for such a late response but consider it compete.

**Comment by franzliedke** [comment]
Thank you @kostassof.

This is now released as part of [version 1.6.0](https://github.com/franzliedke/deis-client/releases/tag/1.6.0), but please note that I [changed the operation names slightly](https://github.com/franzliedke/deis-client/commit/57c30e5a403992744e5969476e23acd9fba69925) for consistency.

**Pull request merged**
